### ISSUE TITLE
Fix Error in profile Page

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#10]
**Describe the bug**
when entering the profile page error appears in the console 

**To Reproduce**
1. Go to the profile page

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/115922140-c2c78180-a491-11eb-8995-e030494c8a83.png)

**Desktop:**
-OS: [windows
-Browser chrome
-Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92 ,
Thank you for information 🙂, however I could not reproduce the above issue.
By the way `screengrabber.js` doesn't seem to be part of this project. Isn't it an extension for chrome?

Could you please take a look? 
Thanks again 😊

**Comment by sinaamini92** [comment]
yes, it's an extension of chrome. thanks
