### ISSUE TITLE
Fix Upload Banner - Edit Profile

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#11]
**Describe the bug**
Upload banner doesn't work when clicking the upload button

**To Reproduce**
1. Go to profile 
2. Click on Edit Profile 
3. Click on the + button on top right
4. Click On upload on the pop-up module 
5. see nothing happens

**Expected behavior**
it's expected to open the Browse window to select a photo as the profile image uploader does.

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/115922577-5305c680-a492-11eb-95b4-6d2e14f9f9f4.png)

**Desktop (please complete the following information):**
- OS: [windows
- Browser chrome
- Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92  ,
I applied the fix, please retest and let me know if any issue.
![image](https://user-images.githubusercontent.com/8446573/116646903-77d2d000-a9a3-11eb-955c-a33378d23e02.png)

Thank you 🙂

**Comment by sinaamini92** [comment]
error persists

**Comment by sinaamini92** [comment]
error fixed. thanks 👌
