### ISSUE TITLE
Banner Typo

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#12]
**Describe the bug**
Banner has two "n"s, but it's written with one "n".

**To Reproduce**
1. Go to Profile
2. Click on Edit Profile
3. Scroll down to the top
4. Click on the + button on top right
5. Typo appears

**Expected behavior**
to  have two "n" in banner

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/115923044-e9d28300-a492-11eb-9f7e-1d3d991575f1.png)

**Desktop (please complete the following information):**
 - OS: [windows
 - Browser chrome
 - Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92  ,
I applied the fix, please retest and let me know if any issue.
![image](https://user-images.githubusercontent.com/8446573/116646954-9df87000-a9a3-11eb-8d00-628204037de1.png)


Thank you 🙂

**Comment by sinaamini92** [comment]
Dear @Qolzam thanks for update 
change "an banner" to "a banner", as "an" only comes before a word starting with a vowel sound

**Comment by Qolzam** [comment]
Thanks @sinaamini92  for checking 🙂. 
I will check it!
