### ISSUE TITLE
Fix Console net::ERR_FILE_NOT_FOUND on Find People Page

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#13]
**Describe the bug**
when scrolling through people on the Find People Page an Error Appears on Console, like below:
social.example.com/storage/540fe5d7-220e-4ccd-8a1f-4bd7c484e199/avatar/a170e10e-ce11-4e57-8046-1ce1d0cfee3f:1 GET https://social.example.com/storage/540fe5d7-220e-4ccd-8a1f-4bd7c484e199/avatar/a170e10e-ce11-4e57-8046-1ce1d0cfee3f net::ERR_NAME_NOT_RESOLVED

**To Reproduce**
1. Go to find People Page
2. Click on Scroll Down
4. See error in Console

**Expected behavior**
to not have errors 

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/115923573-adebed80-a493-11eb-91f3-68b1318b8e27.png)

**Desktop (please complete the following information):**
 - OS: [windows
 - Browser chrome
 - Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92 ,
This case happen when the image address doesn't exist. Handling this error seems not necessary. If you have another idea please let me know. If you also agree that we do not need to fix this issue please close it. 
Thank you 🙂

**Comment by sinaamini92** [comment]
I think we may take care of it later.
