### ISSUE TITLE
Fix Uploaded Profile Image Doesn't Appear after signing out then signing in

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#14]
**Describe the bug**
uploaded profile image doesn't appear after uploading then signing out and then again signing in

**To Reproduce**
1. Go to Profile
2. Click on Edit Profile 
3. Upload an Image for Profile
4. Confirm the image 
5. save the update
6. sign out
7. sign in again
8. see the profile pic doesn't exist

**Expected behavior**
to see the uploaded image after signing in again

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/115924394-e5a76500-a494-11eb-9495-bb1f0b3e26ad.png)

**Desktop (please complete the following information):**
- OS: [windows
 - Browser chrome
 - Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92 ,
I applied the fix, please retest and let me know if any issue.
![image](https://user-images.githubusercontent.com/8446573/116646803-2cb8bd00-a9a3-11eb-84d1-ca721606ea07.png)

Thanks 🙂

**Comment by sinaamini92** [comment]
**Describe the bug**
can't upload an image to profile picture

**To Reproduce**
Steps to reproduce the behavior:
1. Go to Profile
2. Click on Edit Profile 
3. Upload an Image for Profile
4. spinner takes a long time then stops
8. see the profile pic doesn't exist

**Expected behavior**
to see the uploaded image 

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/117070278-bfaa7c00-ad42-11eb-9560-d8246f2eeae7.png)

**Desktop (please complete the following information):**
- OS: [windows
 - Browser chrome (incognito)
 - Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by sinaamini92** [comment]
thanks, the problem is solved 🙌
