### ISSUE TITLE
Fix User suggestion Tab UI

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#16]
**Describe the bug**
text in the user suggestion sidebar collides into each other at a specific resolution

**To Reproduce**
1. Go to Home Page
2. resize the screen to 980px x 685px
3. see the suggestion for you
4. See long names collide into the follow button

**Expected behavior**
not to collide and if size doesn't fit, shorten the names with "..." chars or hide the sidebar entirely 

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/115925676-c7daff80-a496-11eb-8aea-ffc27266b04c.png)

**Desktop (please complete the following information):**
 - OS: [windows 
  - Browser chrome
 - Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92 ,
I applied improvement 
![image](https://user-images.githubusercontent.com/8446573/117265761-c50ce100-ae7e-11eb-8ac8-9052d4d079d1.png)

Please help me to retest. Thanks 🙂

**Comment by sinaamini92** [comment]
tested, works perfectly. thanks.
