### ISSUE TITLE
Fix Loader spinner UX on sign in page

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#18]
**Describe the bug**
after clicking the login button on the signing page the spinner spins out of the box of the button

**To Reproduce**
1. Go to the sign-in page
2. Click on the login 
4. See the out of the box loader spinner

**Expected behavior**
to be located in the center of the button not out of it

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/115926410-09b87580-a498-11eb-87fe-75a65b383978.png)

**Desktop (please complete the following information):**
 - OS: [windows 
  - Browser chrome
 - Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92,
I applied expected improvement.
![image](https://user-images.githubusercontent.com/8446573/117233878-27012280-ae4e-11eb-9cb8-3a9ea70ab5ad.png)

Please help me to retest. Thank you 🙂

**Comment by sinaamini92** [comment]
tested, works properly. I'm closing the issue
