### ISSUE TITLE
Fix: turn off form-autofill in text input of chatbox 

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#36]
**Describe the bug**
turn off form-autofill in chatbox 
clicking on the chat box will cause the suggested text to pop up which is not needed for a chatbox

**To Reproduce**
1. open chatbox
2. Click on the chatbox text input
3. old filled texts appear (the word was typed in the search element before)

**Expected behavior**
not have an autofill option in the text input of a chatbox

**Desktop:**
 - OS: Ubuntu 20.04 LTS
 - Browser: chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Issue is improved.
