### ISSUE TITLE
Fix redirecting after clicking on a notification

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#37]
**Describe the bug**
after clicking on a "like" and "comment" notification alert it redirects you to a blank page

**To Reproduce**
1. click on a notification of a like or comment
2. See error

**Expected behavior**
to see the post or comment and then the comment flash so you see what was the new comment

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/118418033-ff228200-b6cb-11eb-9d90-002b1efc4d2e.png)

**Desktop:**
 - OS: Ubuntu 20.04 LTS
 - Browser: chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92 ,

The issue is fixed. Please help me to retest!

Thank😊
