### ISSUE TITLE
Fix Close option for emojie box

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#39]
**Describe the bug**
there's no way to close the emoji box without clicking on the send button

**To Reproduce**
1. Go to chatbox
2. Click on emojies

**Expected behavior**
to have a close button
**Screenshots**
![Screenshot from 2021-05-17 05-11-56](https://user-images.githubusercontent.com/28287280/118418646-7527e880-b6ce-11eb-8d36-1b973201c42d.png)

**Comment by Qolzam** [comment]
Dear @sinaamini92 ,
Thank you for bug report 🙂,
Could you help me with an idea for the close button? What options we have to make it use friendly?

**Comment by sinaamini92** [comment]
@Qolzam I think clicking on the input element would be a good option to close the emoji box

**Comment by Qolzam** [comment]
Issue is improved.

**Comment by sinaamini92** [comment]
I've double-checked the issue, :+1:
