### ISSUE TITLE
fix Switching between chats

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#40]
**Describe the bug**
if you have one chat open, then open another one, you can't switch to the last one. and you have to close it manually to see the last one
**To Reproduce**
1. open two chats
2. try to switch to another one
3. see it stuck

**Expected behavior**
it's expected to open the new one and close the last one

**Screenshots**
**Desktop:**
 - OS: Ubuntu 20.04 LTS
 - Browser: chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Issues is fixed.
