### ISSUE TITLE
[Bug] In zoom image plugin, back button is not visible

### ISSUE THREAD

**Issue by Abhiranjanchaurasia** [red-gold/ts-ui#5]
**Describe the bug**
1. On the Mobile browser just click at any image post, image zoomed itself but back button not visible as the back button visible at the desktop browser, on parents back/ (device default back) the app moving to a different screen.
**To Reproduce**
1. Go to Home
2. Click on any image post for the zooming the image
3. Now  image zoomed
4. Back, download and others button not appear

**Expected behavior**
There should be the back, download image and other buttons.
**Screenshots**
On Desktop Chrome Browser:
![Screenshot 2019-07-01 at 10 01 37 AM](https://user-images.githubusercontent.com/47344994/60411280-bc478600-9be9-11e9-98e5-2916dab95856.png)
On Mobile chrome browser:
![Nokia-2 2019-07-01 at 10 02 38](https://user-images.githubusercontent.com/47344994/60411299-cbc6cf00-9be9-11e9-8d33-ff5baf856952.jpeg)

**Desktop (please complete the following information):**
 - OS: [MacOs Mojave 10.14.5]
 - Browser [e.g. chrome]
 -Version 75.0.3770.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: [android]
 - OS: [Android 7.1]
 - Browser [Chrome]
 - Version [e.g. 75.0.3770.101]

**Additional context**

**Comment by Qolzam** [comment]
It fixed in new version with toggling picture.
