### ISSUE TITLE
Update upload image UX 

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#7]
**Describe the bug**
the profile upload box UX is not well designed

**To Reproduce**
1. Go to profile
2. Click on upload picture
3. upload dialog pops up
4. the upload box neither have padding nor margins and sticks to left

**Expected behavior**
it needs appropriate padding/margin and needs to fill the box

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/115764641-0dc29580-a3bb-11eb-85ad-dde30def3ae7.png)

**Desktop:**
 - OS: windows 10
 - Browser chrome
 - Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92 ,
I applied the fix, please retest and let me know if any issue.

![image](https://user-images.githubusercontent.com/8446573/116647085-eb74dd00-a9a3-11eb-9295-c6ca807fb64d.png)

Thank you 🙂

**Comment by sinaamini92** [comment]
thanks for taking care of the bug. 🥇
