### ISSUE TITLE
Update Edit Profile Date Picker UX 

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#8]
**Describe the bug**
date picker for Edit Profile doesn't let you choose between years so it needs to reconfigure as it's really troublesome to slide through months to reach a specific year
and there's no Lable/placeholder for the DatePicker Element (I guessed it's for birthday but there's no text claiming it's the birthday or what)

**To Reproduce**
1. Go to profile
2. Click on Edit Profile
3. Scroll down to DatePicker 
4. See DatePicker Element

**Expected behavior**
It needs to let you pick the years directly and it needs to have a label/placeholder on the input element. 

**Screenshots**
![image](https://user-images.githubusercontent.com/28287280/115765763-65adcc00-a3bc-11eb-950c-9765948ec131.png)

**Desktop (please complete the following information):**
 - OS: [windows 
  - Browser chrome
 - Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92 ,
I applied new improvement!

![image](https://user-images.githubusercontent.com/8446573/117233378-3469dd00-ae4d-11eb-9b2a-68e5c1e6e90d.png)

![image](https://user-images.githubusercontent.com/8446573/117233365-2d42cf00-ae4d-11eb-9cc6-9223b7bad3dc.png)
 
 Please help me to retest. Thanks 🙂

**Comment by sinaamini92** [comment]
nice, sucha functional date picker that is. thanks
